### ISSUE TITLE
Unmarshal errors on OrderTrades

### ISSUE THREAD

**Issue by alienatorZ** [pharrisee/poloniex-api#3]
I am receiving "json: cannot unmarshal object into Go value of type poloniex.OrderTrades"

while using the code similiar to

trades, err :=polo.OrderTrades(131531404054)
	if err != nil {
		log.Fatalln(err)
	}
	if len(trades) > 0 {
		fmt.Println(trades)
	}

**Comment by pharrisee** [comment]
To be honest I'm not seeing that at all, bear in mind that you can only see trades involved in orders which you own.

Try turning on debug mode for the api wrapper and let me know if it says, 

{"error":"Order not found, or you are not the person who placed it."}

debug mode can be turned on by calling the .Debug() method before making a request

**Comment by pharrisee** [comment]
I will take a look at the error message coming back as I'd agree that it isn't good enough in this instance.

**Comment by pharrisee** [comment]
OK, I've made a small change to the error handling so that the error returned from poloniex will now be returned to the application.

**Comment by alienatorZ** [comment]
Yes that was it. I think that the error if there were no orders on was causing it to fail in Unmarshal. I usually see it when my program submits a limit order that is immediately executed as a market order. Is there any way to see "resultingTrades" when an order is immediately executed? I haven't had time to go through the sourcecode enough to create a pull request.

Thanks!

**Comment by pharrisee** [comment]
There's nothing in the poloniex API which returns the trades on submitting an order.  The only thing it returns is the OrderNumber and that could then be used to get the trades that make the order.

Although it would be possible (maybe) to do what you ask in the buy/sell methods it would be tiresome taking the different order types into account.

See this from the Poloniex API docs:

> You may optionally set "fillOrKill", "immediateOrCancel", "postOnly" to 1. A fill-or-kill order will either fill in its entirety or be completely aborted. An immediate-or-cancel order can be partially or completely filled, but any portion of the order that cannot be filled immediately will be canceled rather than left on the order book. A post-only order will only be placed if no portion of it fills immediately; this guarantees you will never pay the taker fee on any part of the order that fills.
