### ISSUE TITLE
Examples import the wrong package.

### ISSUE THREAD

**Issue by abrarisme** [pharrisee/poloniex-api#4]
In both of the examples ```"gitlab.com/wmlph/poloniex-api"``` is listed as the poloniex package. I think this was meant to be ```"github.com/pharrisee/poloniex-api"``` correct? The examples work out fine with the second option.

**Comment by abrarisme** [comment]
To clarify "both", I meant the public and private examples.

**Comment by pharrisee** [comment]
yeah, that's a artifact of me moving from gitlab to github.  I'll change them.

**Comment by pharrisee** [comment]
changed
