### ISSUE TITLE
Supporting higher precision floats

### ISSUE THREAD

**Issue by abrarisme** [pharrisee/poloniex-api#5]
Is it possible to support higher precision for decimal points? I saw on the Poloniex API that they're listing 8 decimals points in their response, while order book information through this wrapper only gives 6 points of precision. That ends up being relevant for some pairs like BTC-DOGE. 

I'm not sure if this is a limitation with float64, but if the change is all right with you I can look into it and submit a pull request.

**Comment by pharrisee** [comment]
um, as far as I'm aware there is no limit on the precision of the floats used in the wrapper.  If you're using something like pp to display them that does put a limit on the display of floats of 6 places.  

Can you give me some example of where you think this is an issue?

**Comment by abrarisme** [comment]
That makes more sense. Higher precision ended up being relevant for DOGE-BTC prices at `0.00000101` vs `0.00000110`. Closing because no changes required

**Comment by pharrisee** [comment]
Glad I could clear it up :)
