### ISSUE TITLE
No events on the wss subscription

### ISSUE THREAD

**Issue by vincepii** [pharrisee/poloniex-api#6]
Hello and thanks for this work.

When I try the example from the README (note that there is a small problem with the imports, there should be `time` instead of `log`), and with empty credentials, as in:

```
p := poloniex.NewWithCredentials("", "")
```

I get confirmation about the connection being established and the `subscribe` commands, but I don't receive any events.

After some minutes, this is all the output that I have:

```
2018/01/13 15:38:55 Dial: connection was successfully established with wss://api2.poloniex.com/
2018/01/13 15:38:57 {"command":"subscribe","channel":"1002"}
2018/01/13 15:38:57 {"command":"subscribe","channel":"121"}
```

Is there something wrong in the example?
Or maybe this isn't supposed to be working without credentials (note that when this repository was on gitlab, a few months ago, I could get subscription events with empty credentials)?

I haven't tried with credentials.

**Comment by pharrisee** [comment]
hmm, not sure why you'd use NewWithCredentials and leave them blank, when NewPublicOnly does the same, but anyhoo....

It's a simple fix, the example needed this line added:

p.StartWS()

This line starts a goroutine which reads the raw messages from Poloniex and parses and emits onto various channels.
