### ISSUE TITLE
Question regarding reading messages from WS (ReadMessage -> ReadJSON)

### ISSUE THREAD

**Issue by KLIM8D** [pharrisee/poloniex-api#8]
Sometimes the websocket loses its connection, which is understandable. I looked into mitigating this problem, maybe by reconnecting to the WS API. However I saw that you were already using a library (github.com/mariuspass/recws) that should be able to reconnect in cases like this. What surprises me though, is that you made a change to not use this libs ReadMessage function anymore, how come?

https://github.com/pharrisee/poloniex-api/commit/ccca866a95880eae87bd96af85bbc4b47596a3d2?diff=split

**Comment by pharrisee** [comment]
To be honest it wasn't working as expected, as in the connection still failed.

I'd be more than happy to get a PR with this fixed, it bothers me tremendously. ;)

**Comment by KLIM8D** [comment]
Alright, I'll have a look at it to see if I can come up with something better than what has already been done by this lib :)
